delete __init__.py to get rid of ImportError
pytest causes a following error in Django 2.0:
==================================== ERRORS ====================================
_______________ ERROR collecting certhelper/tests/test_views.py ________________
ImportError while importing test module '/home/travis/build/ptrstn/TkDQMDoctor/certhelper/tests/test_views.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
certhelper/tests/test_views.py:1: in <module>
    from certhelper.tests.custom_asserts import *
certhelper/tests/custom_asserts.py:8: in <module>
    from certhelper.views import *
certhelper/views.py:12: in <module>
    from certhelper.filters import RunInfoFilter, ShiftLeaderRunInfoFilter
certhelper/filters.py:4: in <module>
    from django.forms.extras.widgets import SelectDateWidget
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/django/forms/extras/__init__.py:4: in <module>
    from django.utils.deprecation import RemovedInDjango20Warning
E   ImportError: cannot import name 'RemovedInDjango20Warning'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 1.03 seconds ============================