Fix TypeError: unhashable type: 'list' for PostgreSQL and Django 2.0
When using PostgreSQL and Django 2.0 following error message appears:

TypeError: unhashable type: 'list'

Using tuples instead of lists fixes this problem.