Fix social connection bug
When an user tries to connect his local account with the CERN social
account an error happened because the signature for the
social_account_added signal was wrong

Error Message:
TypeError at /accounts/github/login/callback/
update_user_privilege_by_e_groups() missing 1 required positional
argument: 'user'